export default {
  code: 200,
  msg: "操作成功",
  data: {
    pageNum: 1,
    pageSize: 20,
    total: 4965,
    pages: 249,
    result: [
      {
        id: 5272,
        type: 3,
        difficulty: 1,
        stems: "下列图片的符号是（）\n \n",
        stemsFullText:
          '<p><span style="color: rgb(0, 0, 0);">下列图片的符号是（）</span></p><p><img src="https://tob-biz-test.oss-cn-beijing.aliyuncs.com/static/20210901/20210901.173442.ziva51.png"> </p>',
        analysis: "<p>这个图片是跳房子记号。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5272,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-11 18:05:37",
      },
      {
        id: 5271,
        type: 2,
        difficulty: 2,
        stems: "我录一道多选题 请问现在76人队的当家球星是哪几位\n",
        stemsFullText: "<p>我录一道多选题 请问现在76人队的当家球星是哪几位</p>",
        analysis: "<p>哈登 塞布尔 马克西 恩比德 哈里斯首发阵容</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5271,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-10 12:09:18",
      },
      {
        id: 5270,
        type: 1,
        difficulty: 1,
        stems: "我录一道选项带有图片的题目\n",
        stemsFullText: "<p>我录一道选项带有图片的题目</p>",
        analysis: "<p>解析中含有图片的题目</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [40],
        knowledgePoints: [
          {
            id: 40,
            name: "长江之歌",
            parentId: 39,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七下#第二单元影视金曲#长江之歌",
            questionId: 5270,
            lv: 3,
            coursewareStatus: 0,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-10 11:13:02",
      },
      {
        id: 5269,
        type: 1,
        difficulty: 2,
        stems: "以下书籍哪个不属于四大名著？\n",
        stemsFullText: "<p>以下书籍哪个不属于四大名著？</p>",
        analysis: "<p>诗经不属于四大名著</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [905],
        knowledgePoints: [
          {
            id: 905,
            name: "玩具兵进行曲",
            parentId: 904,
            sort: 1000,
            eduPhase: "1",
            version: 1,
            image: null,
            children: null,
            link: "人音一年级上#第一课好朋友#玩具兵进行曲",
            questionId: 5269,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-08 16:25:06",
      },
      {
        id: 5265,
        type: 1,
        difficulty: 1,
        stems: "测试是否可以正常录入题目\n",
        stemsFullText: "<p>测试是否可以正常录入题目</p>",
        analysis: "<p>正常录入题目的要求是什么</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [1445],
        knowledgePoints: [
          {
            id: 1445,
            name: "瑶家儿童爱唱歌",
            parentId: 1443,
            sort: 999,
            eduPhase: "1",
            version: 5,
            image: null,
            children: null,
            link: "花城一年级下#第二课感知音的高低（三）#瑶家儿童爱唱歌",
            questionId: 5265,
            lv: 3,
            coursewareStatus: 0,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 34,
        updateUserName: "yangyang",
        gmtUpdateTime: "2022-03-07 16:04:04",
      },
      {
        id: 5259,
        type: 1,
        difficulty: 1,
        stems: "这首歌的情感是？\n",
        stemsFullText: "<p>这首歌的情感是？</p>",
        analysis: "<p>。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5259,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 21,
        updateUserName: "宁永恒",
        gmtUpdateTime: "2022-03-07 13:57:07",
      },
      {
        id: 5257,
        type: 1,
        difficulty: 1,
        stems: "这首歌的情绪是\n",
        stemsFullText: "<p>这首歌的情绪是</p>",
        analysis: "<p>。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5257,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-07 13:54:16",
      },
      {
        id: 5256,
        type: 1,
        difficulty: 1,
        stems: "本赛季最佳防守球员是\n",
        stemsFullText: "<p>本赛季最佳防守球员是</p>",
        analysis: "<p>。。。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5256,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-04 11:34:05",
      },
      {
        id: 5249,
        type: 1,
        difficulty: 2,
        stems: "02有三十个字符这里有三十个字符这里有三十个字符这里有三十个\n\n",
        stemsFullText:
          '<p>02有三十个字符这里有三十个字符这里有三十个字符这里有三十个</p><p><img src="https://piano-fish-adm-prod.oss-cn-beijing.aliyuncs.com/static/2022-03-02/oss-fe7dd0d95abb9c78e6e34c6e6ead79a8.jpg" height="100" width="100"></p>',
        analysis: "<p>。。。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [905],
        knowledgePoints: [
          {
            id: 905,
            name: "玩具兵进行曲",
            parentId: 904,
            sort: 1000,
            eduPhase: "1",
            version: 1,
            image: null,
            children: null,
            link: "人音一年级上#第一课好朋友#玩具兵进行曲",
            questionId: 5249,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-03 10:19:16",
      },
      {
        id: 5248,
        type: 1,
        difficulty: 1,
        stems:
          "这里有三十个字符这里有三十个字符这里有三十个字符这里有三十个\n\n",
        stemsFullText:
          '<p>这里有三十个字符这里有三十个字符这里有三十个字符这里有三十个</p><p><img src="https://piano-fish-adm-prod.oss-cn-beijing.aliyuncs.com/static/2022-03-02/oss-b697174431477ad069850d7924f42fe2.jpg" height="100" width="100"></p>',
        analysis: "<p>。。。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [905],
        knowledgePoints: [
          {
            id: 905,
            name: "玩具兵进行曲",
            parentId: 904,
            sort: 1000,
            eduPhase: "1",
            version: 1,
            image: null,
            children: null,
            link: "人音一年级上#第一课好朋友#玩具兵进行曲",
            questionId: 5248,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-03 10:18:36",
      },
      {
        id: 5245,
        type: 1,
        difficulty: 3,
        stems: "我录入一道选项中带有图片的题目\n",
        stemsFullText: "<p>我录入一道选项中带有图片的题目</p>",
        analysis: "<p>。。。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [905],
        knowledgePoints: [
          {
            id: 905,
            name: "玩具兵进行曲",
            parentId: 904,
            sort: 1000,
            eduPhase: "1",
            version: 1,
            image: null,
            children: null,
            link: "人音一年级上#第一课好朋友#玩具兵进行曲",
            questionId: 5245,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-02 10:40:50",
      },
      {
        id: 5244,
        type: 1,
        difficulty: 1,
        stems:
          "录一个题目这里一共有三十个字符查看题目展示是否异常二十六二四\n\n",
        stemsFullText:
          '<p>录一个题目这里一共有三十个字符查看题目展示是否异常二十六二四</p><p><img src="https://piano-fish-adm-prod.oss-cn-beijing.aliyuncs.com/static/2022-03-02/oss-6262abe0b39017ccc74b47056b360d36.jpeg" height="60" width="160"></p>',
        analysis: "<p>解析必须要超出10个字符</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [905],
        knowledgePoints: [
          {
            id: 905,
            name: "玩具兵进行曲",
            parentId: 904,
            sort: 1000,
            eduPhase: "1",
            version: 1,
            image: null,
            children: null,
            link: "人音一年级上#第一课好朋友#玩具兵进行曲",
            questionId: 5244,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-03-02 10:38:16",
      },
      {
        id: 5240,
        type: 3,
        difficulty: 2,
        stems: "填空题验证最后一个选项\n",
        stemsFullText: "<p>填空题验证最后一个选项</p>",
        analysis: "<p>。。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5240,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-02-16 12:15:18",
      },
      {
        id: 5238,
        type: 4,
        difficulty: 2,
        stems: "恩比德在76人队吗\n",
        stemsFullText: "<p>恩比德在76人队吗</p>",
        analysis: "<p>。。。。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5238,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-02-16 11:52:22",
      },
      {
        id: 5237,
        type: 2,
        difficulty: 1,
        stems: "多选\n",
        stemsFullText: "<p>多选</p>",
        analysis: "<p>。。。。。。。。。</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [4],
        knowledgePoints: [
          {
            id: 4,
            name: "中华人民共和国国歌",
            parentId: 2,
            sort: 999,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#中华人民共和国国歌",
            questionId: 5237,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-02-16 11:39:03",
      },
      {
        id: 5236,
        type: 2,
        difficulty: 1,
        stems: "我国四大名著是：\n",
        stemsFullText: "<p>我国四大名著是：</p>",
        analysis: "<p>这是答案的解析略略略</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5236,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-02-16 11:28:20",
      },
      {
        id: 5231,
        type: 3,
        difficulty: 1,
        stems: "回归测试填空题\n",
        stemsFullText: "<p>回归测试填空题</p>",
        analysis: "<p>这里是答案解析</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5231,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-01-27 19:29:53",
      },
      {
        id: 5225,
        type: 2,
        difficulty: 2,
        stems: "建议多选题至少保留两个选项。\n",
        stemsFullText: "<p>建议多选题至少保留两个选项。</p>",
        analysis: "<p>这里是答案解析</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5225,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-01-26 16:16:21",
      },
      {
        id: 5223,
        type: 3,
        difficulty: 1,
        stems: "测试最新的填空题的答案只能有多个选项0126\n",
        stemsFullText: "<p>测试最新的填空题的答案只能有多个选项0126</p>",
        analysis: "<p>fdsafdsa</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [16],
        knowledgePoints: [
          {
            id: 16,
            name: "牧歌",
            parentId: 14,
            sort: 999,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第三单元草原牧歌#牧歌",
            questionId: 5223,
            lv: 3,
            coursewareStatus: 0,
            opernStatus: 0,
            semester: 0,
          },
        ],
        updateUserId: 21,
        updateUserName: "宁永恒",
        gmtUpdateTime: "2022-01-26 14:48:18",
      },
      {
        id: 5221,
        type: 3,
        difficulty: 2,
        stems: "test带有图片的选项\n\n",
        stemsFullText:
          '<p>test带有图片的选项</p><p><img src="https://piano-fish-adm-prod.oss-cn-beijing.aliyuncs.com/static/2022-01-25/oss-b98c394860c4530365b8811c0d88be73.jpeg" height="100" width="100"></p>',
        analysis: "<p>22</p>",
        voideAttId: null,
        voideAttInfo: null,
        opernAttId: null,
        opernAttInfo: null,
        answers: null,
        knowledgePointIds: [3],
        knowledgePoints: [
          {
            id: 3,
            name: "彩色的中国",
            parentId: 2,
            sort: 1000,
            eduPhase: "2",
            version: 0,
            image: null,
            children: null,
            link: "人音七上#第一单元歌唱祖国#彩色的中国",
            questionId: 5221,
            lv: 3,
            coursewareStatus: 1,
            opernStatus: 1,
            semester: 0,
          },
        ],
        updateUserId: 20,
        updateUserName: "张文特",
        gmtUpdateTime: "2022-01-25 17:23:43",
      },
    ],
    expansion: null,
  },
  serverTime: 1647408531314,
};
